/*
  The knowledge graph behind the neural index. Top-level nodes orbit the
  core; clicking one dives into its sub-brain. Leaf nodes show a hover card
  (info/stat/tags) and may open a link on click (href). A node's `orbiters`
  are logo images that circle the core (neon-tinted) while its view is open.
*/
import {
  reactjs,
  nextjs,
  javascript,
  typescript,
  redux,
  tailwind,
  html,
  css,
  nodejs,
  express,
  php,
  cs,
  dotnet,
  sql,
  aws,
  docker,
  kobernetes,
  git,
  wordpress,
  figma,
  storybook,
} from '../../assets';

export const BRAIN_GRAPH = {
  label: 'NEURAL INDEX',
  sub: 'muhannad · alobaidi',
  children: [
    {
      label: 'ABOUT',
      sub: 'the human',
      info: 'Muhannad Alobaidi — game developer turned full-stack & mobile developer. Since 2019 I have been turning visions into tangible digital reality, pairing front-end craft with back-end and cloud engineering.',
      stat: 'full-stack · mobile · since 2019',
      tags: ['Front-end', 'Back-end', 'Mobile', 'Cloud'],
    },
    {
      label: 'SKILLS',
      sub: 'tech stack',
      info: 'The technologies wired into the cortex — frontend to cloud.',
      stat: '20+ technologies',
      orbiters: [
        reactjs,
        nextjs,
        javascript,
        typescript,
        redux,
        tailwind,
        html,
        css,
        nodejs,
        express,
        php,
        cs,
        dotnet,
        sql,
        aws,
        docker,
        kobernetes,
        git,
        wordpress,
        figma,
        storybook,
      ],
      children: [
        {
          label: 'FRONTEND',
          sub: 'react · next · ts',
          info: 'Building responsive, accessible, performant interfaces.',
          stat: 'core strength',
          tags: ['React', 'React Native', 'Next.js', 'TypeScript', 'JavaScript', 'Redux', 'Tailwind', 'HTML', 'CSS', 'Storybook'],
        },
        {
          label: 'BACKEND',
          sub: 'node · php · .net',
          info: 'APIs and server-side logic behind the interfaces.',
          stat: 'full-stack capable',
          tags: ['Node.js', 'Express', 'PHP', 'C#', '.NET', 'SQL', 'Python', 'Django'],
        },
        {
          label: 'CLOUD · DEVOPS',
          sub: 'aws · docker · k8s',
          info: 'Shipping and running things reliably in the cloud.',
          stat: 'deploy ready',
          tags: ['AWS', 'Docker', 'Kubernetes', 'Git'],
        },
        {
          label: 'CMS',
          sub: 'wordpress · headless',
          info: 'Content platforms, classic and headless, REST-wired to modern frontends.',
          stat: 'many sites shipped',
          tags: ['WordPress', 'Headless CMS', 'REST API'],
        },
        {
          label: 'DESIGN · 3D',
          sub: 'figma · blender · unity',
          info: 'From UI design systems to 3D characters and game engines.',
          stat: 'game-dev roots',
          tags: ['Figma', 'Blender', 'Unity', 'Photoshop', '3D Animation'],
        },
      ],
    },
    {
      label: 'EXPERIENCE',
      sub: 'work history',
      info: 'From game studios to leading front-end development — since 2019.',
      stat: '2019 — present',
      children: [
        {
          label: 'FRONTEND DEV',
          sub: 'SEK Oy',
          info: 'Building and maintaining high-quality websites, AI tools and digital experiences. Leading front-end development from concept to delivery.',
          stat: 'NOV 2024 — PRESENT',
          tags: ['React', 'Next.js', 'TypeScript', 'AI', 'AWS', 'Accessibility', 'SEO'],
        },
        {
          label: 'WEB DEV',
          sub: 'SEK Oy',
          info: 'Built, styled and shipped websites, design systems and digital experiences for a diverse array of client projects.',
          stat: 'SEP 2021 — NOV 2024',
          tags: ['React', 'Next.js', 'WordPress', 'Headless CMS', 'SCSS', 'Storybook'],
        },
        {
          label: 'TRAINEE',
          sub: 'SEK Oy',
          info: 'Hands-on start in web development: landing pages and small client sites in vanilla HTML/CSS/JS, learning from senior developers.',
          stat: 'MAR 2021 — SEP 2021',
          tags: ['JavaScript', 'HTML', 'SCSS', 'WordPress', 'Node.js'],
        },
        {
          label: 'GAME DEV',
          sub: 'Gilgamish studio',
          info: 'Designed and developed games for a startup: UI/UX, 3D characters and core mechanics in Unity.',
          stat: '2019 — 2020',
          tags: ['Unity', 'C#', 'Blender', 'Game Design', '3D Animation'],
        },
      ],
    },
    {
      label: 'PROJECTS',
      sub: 'selected work',
      info: 'A few things shipped into the world — most open in a new tab.',
      stat: '5 highlighted',
      children: [
        {
          label: 'SALOMAA',
          sub: 'full site renewal',
          info: 'Complete website overhaul for a Finnish food-products company: design, functionality and performance.',
          stat: 'salomaa.fi',
          href: 'https://www.salomaa.fi/',
          tags: ['WordPress', 'Tailwind', 'GSAP', 'PHP'],
        },
        {
          label: 'LAGERBLAD',
          sub: 'headless wordpress',
          info: 'WordPress as a headless CMS with a Next.js frontend for LagerBlad Foods.',
          stat: 'lagerbladfoods.fi',
          href: 'https://www.lagerbladfoods.fi/',
          tags: ['Next.js', 'React', 'Headless CMS', 'REST API'],
        },
        {
          label: 'SOLARFOODS',
          sub: 'scroll story',
          info: 'An on-scroll brand-story sequence that walks visitors through the company journey step by step.',
          stat: 'solarfoods.com',
          href: 'https://solarfoods.com/our-story/',
          tags: ['WordPress', 'jQuery', 'CSS'],
        },
        {
          label: 'SEK RENEWAL',
          sub: 'headless migration',
          info: 'Company website renewal, transforming WordPress into a headless-CMS architecture.',
          stat: 'sek.fi',
          href: 'https://www.sek.fi/',
          tags: ['Next.js', 'TypeScript', 'WordPress', 'API'],
        },
        {
          label: 'THIS SITE',
          sub: 'react three fiber',
          info: 'The portfolio you are looking at: React, Vite, three.js and a ported neural core.',
          stat: 'you are here',
          tags: ['React', 'Vite', 'React Three Fiber', 'Blender'],
        },
      ],
    },
    {
      // TODO(muhannad): when formal education entries exist, add a
      // `children: [...]` array here (label/sub/info/stat/tags per entry)
      // and this node becomes a dive-able category again
      label: 'EDUCATION',
      sub: 'learning path',
      info: 'Self-directed — from game development into modern web engineering, learning in production one shipped project at a time.',
      stat: '2019 — present · always learning',
      tags: ['Web', 'Cloud', 'AI', '3D'],
    },
    {
      label: 'CONTACT',
      sub: 'open a channel',
      info: 'Direct links — click a node to transmit.',
      stat: '3 channels',
      children: [
        {
          label: 'LINKEDIN',
          sub: 'professional link',
          info: 'linkedin.com/in/muhannad-alobaidi — click to open the profile.',
          stat: '▸ opens in new tab',
          href: 'https://www.linkedin.com/in/muhannad-alobaidi/',
        },
        {
          label: 'EMAIL',
          sub: 'direct transmission',
          info: 'muhannad.alobaidi@yahoo.com — click to compose.',
          stat: '▸ opens mail client',
          href: 'mailto:muhannad.alobaidi@yahoo.com',
        },
        {
          label: 'PHONE',
          sub: 'voice channel',
          info: '+358 40 165 6648 — click to call.',
          stat: '▸ tel link',
          href: 'tel:+358401656648',
        },
      ],
    },
  ],
};
