/*
  The knowledge graph behind the neural index. Top-level nodes orbit the
  core; clicking one dives into its sub-brain. Leaf nodes show a hover card
  (info/stat/tags) and may open a link on click (href). A node's `orbiters`
  are logo images that circle the core (neon-tinted) while its view is open.
*/
import {
  reactjs,
  nextjs,
  javascript,
  typescript,
  redux,
  tailwind,
  html,
  css,
  nodejs,
  express,
  php,
  cs,
  dotnet,
  sql,
  aws,
  docker,
  kobernetes,
  git,
  wordpress,
  figma,
  storybook,
  linkedin,
  email,
  phone,
} from '../../assets';

export const BRAIN_GRAPH = {
  label: 'NEURAL INDEX',
  sub: 'muhannad · alobaidi',
  children: [
    {
      label: 'ABOUT',
      sub: 'the human',
      info: 'Muhannad Alobaidi — computer engineer turned full-stack & mobile developer. Click to open the dossier: portrait, story, off-hours and CV.',
      stat: 'full-stack · mobile · AI',
      tags: ['Frontend', 'Mobile', 'Backend', 'Cloud', 'AI'],
      // rich content rendered by the AboutDossier panel when this node is focused
      dossier: {
        role: 'Full-stack & Mobile Developer',
        bio: [
          "I'm Muhannad — a computer engineer who fell for the craft of building things people actually use. From game studios in Baghdad to leading frontend at Baity, I've spent years turning ideas into products across web, mobile, cloud and AI.",
          "I care about the details most people never notice — the half-second of polish, the interaction that feels alive. When the editor closes, you'll find me under a barbell, deep in a game or a film, or with a pen in hand.",
        ],
        languages: ['English', 'Arabic', 'Finnish'],
        hobbies: [
          { label: 'Gym workout', icon: '🏋' },
          { label: 'Gaming', icon: '🎮' },
          { label: 'Movies', icon: '🎬' },
          { label: 'Drawing', icon: '✏️' },
          { label: 'Tattoo artist', icon: '🖋' },
        ],
        cv: '/Muhannad-Alobaidi-CV.pdf',
      },
    },
    {
      label: 'SKILLS',
      sub: 'tech stack',
      info: 'The technologies wired into the cortex — frontend to cloud.',
      stat: '20+ technologies',
      orbiters: [
        reactjs,
        nextjs,
        javascript,
        typescript,
        redux,
        tailwind,
        html,
        css,
        nodejs,
        express,
        php,
        cs,
        dotnet,
        sql,
        aws,
        docker,
        kobernetes,
        git,
        wordpress,
        figma,
        storybook,
      ],
      children: [
        {
          label: 'FRONTEND',
          sub: 'react · vue · next',
          info: 'Building responsive, accessible, performant interfaces across both major ecosystems.',
          stat: 'core strength',
          tags: ['React', 'Next.js', 'Vue', 'Nuxt', 'TypeScript', 'JavaScript', 'Redux', 'Tailwind', 'HTML', 'CSS', 'Storybook'],
        },
        {
          label: 'MOBILE',
          sub: 'flutter · react native',
          info: 'Cross-platform mobile apps — production Flutter work on the Baity app.',
          stat: 'cross-platform',
          tags: ['Flutter', 'Dart', 'React Native'],
        },
        {
          label: 'BACKEND',
          sub: 'node · .net · django',
          info: 'APIs and server-side logic behind the interfaces.',
          stat: 'full-stack capable',
          tags: ['Node.js', 'Express', 'PHP', 'C#', 'ASP.NET', 'Python', 'Django', 'SQL'],
        },
        {
          label: 'AI · SECURITY',
          sub: 'llms · pentesting',
          info: 'AI-powered tools built with LLMs, prompt engineering and MCPs; trained in ethical hacking and risk assessment.',
          stat: 'shipping AI tools',
          tags: ['LLMs', 'Prompt engineering', 'MCP', 'TensorFlow', 'PyTorch', 'Pentesting'],
        },
        {
          label: 'CLOUD · DEVOPS',
          sub: 'aws · docker · k8s',
          info: 'Shipping and running things reliably in the cloud.',
          stat: 'AWS Cloud Practitioner certified',
          tags: ['AWS', 'Docker', 'Kubernetes', 'Git', 'CI/CD', 'Jira'],
        },
        {
          label: 'CMS',
          sub: 'wordpress · headless',
          info: 'Content platforms, classic and headless, REST-wired to modern frontends.',
          stat: 'many sites shipped',
          tags: ['WordPress', 'Headless CMS', 'REST API'],
        },
        {
          label: 'DESIGN · 3D',
          sub: 'figma · blender · unity',
          info: 'From UI design systems to 3D characters and game engines.',
          stat: 'game-dev roots',
          tags: ['Figma', 'Blender', 'Unity', 'Photoshop', '3D Animation'],
        },
      ],
    },
    {
      label: 'EXPERIENCE',
      sub: 'work history',
      info: 'From Helsinki web studios to leading frontend development at Baity.',
      stat: '2021 — present',
      children: [
        {
          label: 'LEAD FRONTEND',
          sub: 'Baity',
          info: 'Leading a team of 2 frontend developers on the Baity platform — website, dashboard and Flutter mobile app — with backend support in C#/ASP.NET.',
          stat: 'FEB 2026 — PRESENT · Baghdad',
          tags: ['Vue', 'Nuxt', 'Flutter', 'Dart', 'C#', 'ASP.NET', 'Leadership'],
        },
        {
          label: 'FRONTEND DEV',
          sub: 'SEK Oy',
          info: 'Led technical development of complex web applications and built AI-powered tools with LLMs, prompt engineering and MCPs.',
          stat: 'NOV 2024 — SEP 2025 · Helsinki',
          tags: ['React', 'Next.js', 'React Native', 'TypeScript', 'Tailwind', 'LLMs', 'CI/CD'],
        },
        {
          label: 'WEB DEV',
          sub: 'SEK Oy',
          info: 'Built and deployed client web projects and internal tooling; improved performance, SEO and component architecture across sites.',
          stat: 'SEP 2021 — NOV 2024 · Helsinki',
          tags: ['React', 'Next.js', 'WordPress', 'PHP', 'SCSS', 'SEO'],
        },
        {
          label: 'TRAINEE',
          sub: 'SEK Oy',
          info: 'Built landing pages, small websites and UI elements in vanilla HTML/CSS/JS; maintained Node.js applications.',
          stat: 'MAR 2021 — SEP 2021 · Helsinki',
          tags: ['JavaScript', 'HTML', 'CSS', 'Node.js'],
        },
      ],
    },
    {
      label: 'PROJECTS',
      sub: 'selected work',
      info: 'A few things shipped into the world — most open in a new tab.',
      stat: '8 highlighted',
      children: [
        {
          label: 'BAITY APP',
          sub: 'flutter mobile',
          info: 'Cross-platform mobile app for the Baity real-estate platform — Flutter on iOS and Android, Arabic-first with full RTL.',
          stat: 'in production',
          tags: ['Flutter', 'Dart', 'REST API', 'ASP.NET'],
        },
        {
          label: 'BAITY WEBSITE',
          sub: 'vue · nuxt',
          info: 'The public face of the Baity platform — Nuxt SSR, bilingual AR/EN, built by the frontend team I lead.',
          stat: 'in production',
          tags: ['Vue', 'Nuxt', 'TypeScript', 'SSR'],
        },
        {
          label: 'BAITY DASHBOARD',
          sub: 'admin platform',
          info: 'The control room of the Baity platform — listings, agents, analytics and role-based access on Vue/Nuxt.',
          stat: 'in production',
          tags: ['Vue', 'Nuxt', 'REST API', 'Charts'],
        },
        {
          label: 'SALOMAA',
          sub: 'full site renewal',
          info: 'Complete website overhaul for a Finnish food-products company: design, functionality and performance.',
          stat: 'salomaa.fi',
          href: 'https://www.salomaa.fi/',
          tags: ['WordPress', 'Tailwind', 'GSAP', 'PHP'],
        },
        {
          label: 'LAGERBLAD',
          sub: 'headless wordpress',
          info: 'WordPress as a headless CMS with a Next.js frontend for LagerBlad Foods.',
          stat: 'lagerbladfoods.fi',
          href: 'https://www.lagerbladfoods.fi/',
          tags: ['Next.js', 'React', 'Headless CMS', 'REST API'],
        },
        {
          label: 'SOLARFOODS',
          sub: 'scroll story',
          info: 'An on-scroll brand-story sequence that walks visitors through the company journey step by step.',
          stat: 'solarfoods.com',
          href: 'https://solarfoods.com/our-story/',
          tags: ['WordPress', 'jQuery', 'CSS'],
        },
        {
          label: 'SEK RENEWAL',
          sub: 'headless migration',
          info: 'Company website renewal, transforming WordPress into a headless-CMS architecture.',
          stat: 'sek.fi',
          href: 'https://www.sek.fi/',
          tags: ['Next.js', 'TypeScript', 'WordPress', 'API'],
        },
        {
          label: 'THIS SITE',
          sub: 'react three fiber',
          info: 'The portfolio you are looking at: React, Vite, three.js and a ported neural core.',
          stat: 'you are here',
          tags: ['React', 'Vite', 'React Three Fiber', 'Blender'],
        },
      ],
    },
    {
      label: 'EDUCATION',
      sub: 'learning path',
      info: 'A computer engineering degree, then specializations from game development to AI and security.',
      stat: 'B.Eng + 4 programs',
      children: [
        {
          label: 'ETHICAL HACKING',
          sub: 'Metropolia Open Uni',
          info: 'Penetration testing, vulnerability scanning and risk assessment, with documented findings and remediation.',
          stat: 'MAR 2023 — MAR 2024 · Helsinki',
          tags: ['Pentesting', 'Security', 'Risk assessment'],
        },
        {
          label: 'AI DEVELOPMENT',
          sub: 'Metropolia Open Uni',
          info: 'Developing, training and evaluating machine-learning models; data preparation and model optimization with TensorFlow and PyTorch.',
          stat: 'MAR 2023 — MAY 2023 · Helsinki',
          tags: ['TensorFlow', 'PyTorch', 'ML'],
        },
        {
          label: 'WEB DEV',
          sub: 'Zero To Mastery',
          info: 'Full-stack project work with React, Node.js and MongoDB.',
          stat: 'MAR 2020 — MAR 2021 · online',
          tags: ['React', 'Node.js', 'MongoDB'],
        },
        {
          label: 'GAME DEV',
          sub: 'Amiadu',
          info: 'Designed and developed multiple game projects with Unity, C# and Blender.',
          stat: 'MAR 2018 — MAR 2019 · Helsinki',
          tags: ['Unity', 'C#', 'Blender'],
        },
        {
          label: 'COMPUTER ENG',
          sub: 'Almamon University',
          info: 'Bachelor of Computer Engineering — software engineering, project management and C#.',
          stat: 'SEP 2008 — JUN 2012 · Baghdad',
          tags: ['Software engineering', 'Project management', 'C#'],
        },
      ],
    },
    {
      label: 'CONTACT',
      sub: 'open a channel',
      info: 'Direct links — click a node to transmit.',
      stat: '3 channels',
      children: [
        {
          label: 'LINKEDIN',
          sub: 'professional link',
          info: 'linkedin.com/in/muhannad-alobaidi — click to open the profile.',
          stat: '▸ opens in new tab',
          href: 'https://www.linkedin.com/in/muhannad-alobaidi/',
          particleIcon: linkedin,
        },
        {
          label: 'EMAIL',
          sub: 'direct transmission',
          info: 'muhannad.alobaidi@yahoo.com — click to compose.',
          stat: '▸ opens mail client',
          href: 'mailto:muhannad.alobaidi@yahoo.com',
          particleIcon: email,
        },
        {
          label: 'PHONE',
          sub: 'voice channel',
          info: '+358 40 165 6648 — click to call.',
          stat: '▸ tel link',
          href: 'tel:+358401656648',
          particleIcon: phone,
        },
      ],
    },
  ],
};
